<header>
   <p  style='font-size:36px;font-family:Arial; color:#F0F0F0; background-color: #00233c; padding-left: 20pt; padding-top: 20pt;padding-bottom: 10pt; padding-right: 20pt;'>
       Vantage Analytic Library Demo
  <br>
       <img id="teradata-logo" src="https://storage.googleapis.com/clearscape_analytics_demo_data/DEMO_Logo/teradata.svg" alt="Teradata" style="width: 125px; height: auto; margin-top: 20pt;">
    </p>
</header>
<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>Descriptive Statistics and Data Transformation Functions</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The following functions are currently available in the Vantage and are a part of the Vantage Analytic Library.</p>

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>Descriptive Statistics</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Values Analysis</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>    
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Data Types</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Count</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Number NULLs, Positive, Negative and Unique, Zero and Blank values</li>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Univariate Statistical Analysis</b></p>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Count/Minimum/Maximum/Mean</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Standard Deviation</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Standard Mean Error</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Variance & Coefficient of Variance</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Skewness & Kurtosis </li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Uncorrected Sum of Squares</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Corrected Sum of Squares</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Modes</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Quantiling & Ranking</li>
    <li style = 'font-size:14px;font-family:Arial;color:#00233C'>Top 10/Bottom 10 Percentiles*</li>
    <li style = 'font-size:14px;font-family:Arial;color:#00233C'>Deciles/Quartiles/Tertiles*</li>
    <li style = 'font-size:14px;font-family:Arial;color:#00233C'>Top 5/Bottom 5 Ranks and Values*</li>
<p>
    
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Distribution Analysis</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Frequency of Discrete Variables</b></p>

 <table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Style</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>basic</td>
    <td>Counts frequencies of individual column values (default).</td>
  </tr>
  <tr>
    <td>pairwise</td>
    <td>Counts frequencies of pair-wise combinations of values of selected columns rather than individually. Not available if the cumulative option is selected.</td>
  </tr>
  <tr>
    <td>crosstab</td>
    <td>Counts frequencies of combinations of values of selected columns rather than individually.</td>
  </tr>
</table>
   
<p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Histograms of Continuous Variables</b></p>

  <table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Option</th>
    <th>Description/Example</th>
  </tr>
  <tr>
    <td>bins</td>
    <td>The number of equal width bins to create.</td>
  </tr>
  <tr>
    <td></td>
    <td>For example, bins=5. If multiple columns are requested, multiple bin sizes may be specified, such as bins=5, 10. If fewer sizes are specified than columns, left-over columns are associated with the default size of 10 bins.</td>
  </tr>
  <tr>
    <td>widths</td>
    <td>The width of the bins to create. </td>
  </tr>
  <tr>
    <td></td>
    <td>For example, widths=100. If multiple columns are requested, multiple widths must be specified, such as widths=5, 10. If fewer sizes are specified than columns, an error message displays.</td>
  </tr>
  <tr>
    <td>quantiles</td>
    <td>The number of approximately equally populated bins to create.</td>
  </tr>    
  <tr>
    <td></td>
    <td>For example, quantiles=10. If multiple columns are requested, multiple quantile sizes may be specified, such as quantiles=5, 10. If fewer sizes are specified than columns, left-over columns are associated with the default size of 10 quantiles.</td>
  </tr>
  <tr>
    <td>boundaries</td>
    <td>Specific boundaries that define the bins.</td>
  </tr>
  <tr>
    <td></td>
    <td>For example, boundaries=0,50,100,150 provides 3 bins between 0 and 150 (0 to 50, 50 to 100, and 100 to 150). If multiple columns are requested, multiple sets of parameters must be specified, such as boundaries={0, 50000, 100000, 150000}, {0, 50, 100}.</td>
  </tr>
  <tr>
    <td>binwithminmax</td>
    <td>The number of bins spanning a range specified by the minimum and maximum values.</td>
  </tr>
  <tr>
    <td></td>
    <td>For example, binwithminmax=5,0,200 creates 5 bins ranging from 0 to 200. If multiple columns are requested, multiple sets of parameters must be specified, such as binwithminmax={10, 0, 200000}, {5, 0, 100}.</td>
  </tr>      
</table>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A separate (Adaptive Histogram) analysis is offered to intelligently bin data by offering options to further subdivide the distribution.</p> 

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Overlap Analysis</b></p>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'> Index/Key Column Consistency</li>
<p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Data Explorer</b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Performs basic statistical analysis on a set of tables and selected columns within any database in the SQL Engine.</p>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Values - Every column in the set of input tables* </li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Univariate Statistics - Every column of numeric or date type*</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Frequencies - Every column that has less than or equal to a number of unique values*</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Histograms - Every numeric or date type column that has more than a number of unique values*</li>
<p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Matrix Analysis</b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Create a matrix for input to Linear Regression (or Factor Analysis in the next release) or analysis of any of the following types of matrices:</p>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>SSCP = sum-of-squares-and-cross-products matrix (the default)</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>ESSCP = Extended-sum-of-squares-and-cross-products matrix</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>CSSCP = Corrected-sum-of-squares-and-cross-products matrix</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>COV = Covariance matrix</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>COR = Correlation matrix</li>
<p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Text Field Analysis</b></p>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Analyze character data to determine type</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Extended numeric and Unicode analysis</li>
<p>
    
<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>Variable Transformation Functions</b></p>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Variable Transformation analysis reads a single table or view and produces a Select, Create Table, or Create View statement containing transformed columns.  Each function below can be called individually or in any combination. </p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Bin Coding</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Bin Coding replaces a continuous numeric column with a categorical one and produce ordinal values (for example, numeric categorical values where order is meaningful). Bin Coding uses the same techniques used in Histogram analysis, allowing you to choose between equal-width bins, equal-width bins with a user-specified minimum and maximum range, bins with a user-specified width, evenly distributed bins, or bins with user-specified boundaries.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Design Coding</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Design Coding is useful when a categorical data element must be re-expressed as one or more numeric data elements, creating a binary numeric field for each categorical data value. Design coding is offered in two forms: dummy-coding and contrast-coding.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Recoding</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Recoding a categorical data column is done to re-express existing values of a column (variable) into a new coding scheme or to correct data quality problems and focus an analysis on a particular value. It allows for mapping individual values, NULL values, or any number of remaining values (ELSE option) to a new value, a NULL value or the same value.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Rescaling</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Rescaling limits the upper and lower boundaries of the data in a continuous numeric column using a linear rescaling function based on maximum and minimum data values. Rescale is useful with algorithms that require or work better with data within a certain range.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Sigmoid Transformation</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A Sigmoid transformation provides rescaling of continuous numeric data in a more sophisticated way than the Rescaling transformation function. In a Sigmoid transformation a numeric column is transformed using a type of sigmoid or s-shaped function. </p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Z-Score Transformation</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Similar to a Sigmoid transformation, a Z-Score transformation provides rescaling of continuous numeric data in a more sophisticated way than a Rescaling transformation.  Z-Score transforms each column value into the number of standard deviations from the mean value of the column.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>NULL Value Replacement</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>NULL value replacement is offered as a transformation function. A literal value, the mean, median, mode, or an imputed value joined from another table can be used as the replacement value. The median value can be requested with or without averaging of two middle values when there is an even number of values.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Formula Derivations</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Derive transformation requires the free-form transformation be specified as a formula using the following operators, arguments, and functions:  +, -, **, *, /, %, (, ), x, y, z, abs, exp, ln, log, sqrt</p>

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>Vantage Analytic Library - Call Structure</b></p>

call val.td_analyze('\<function name\>','\<database=database name\>;\<tablename=table name\>;\<columns=column1, column2\>,'\<param1\>=\<value1\>;\<param2\>=\<value2\>...');

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'> <b>1. Connect to Vantage </b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>You will be prompted to provide the password. Enter your password, press Enter, then use down arrow to go to next cell.</p>

In [ ]:
%connect local, hidewarnings=true

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Setup for execution of notebook. Begin running steps with Shift + Enter keys.</p>

In [ ]:
Set query_band='DEMO=VAL_Descriptive_Statistics_SQL.ipynb;' update for session;

<hr style="height:2px;border:none;background-color:#00233C;">
<p style = 'font-size:20px;font-family:Arial;color:#00233C'> <b>2. Getting Data for This Demo:</b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>We have provided data for this demo on cloud storage. You can either run the demo using foreign tables to access the data without any storage on your environment or download the data to local storage, which may yield faster execution. Still, there could be considerations of available storage. Two statements are in the following cell, and one of them is commented out. You may switch between the modes by changing the comment string.</p>

In [ ]:
---call get_data('DEMO_Financial_cloud'); ---takes about 35 seconds
call get_data('DEMO_Financial_local'); ---takes about 100 seconds

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Optional step – if you want to see status of databases/tables created and space used.</p>

In [ ]:
call space_report();  -- optional, takes about 10 seconds

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>Demo data - Financial Customers/Accounts/Transactions</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The following data has been put into the DEMO_Financial database for the examples in the three different Jupyter Notebooks.  It's a simplistic fictitious dataset of banking customers (approx. 10K rows), Accounts (approx. 20K rows) and Transactions (approx. 1Million rows).  They are related to each other in the following ways:</p>

<img src= "images/DemoData.png">

In [ ]:
SELECT TOP 5 * FROM DEMO_Financial.Customer;

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Below command shows metadata details for the table.</p>

In [ ]:
%meta

In [ ]:
SELECT TOP 5 * FROM DEMO_Financial.Accounts;

In [ ]:
SELECT TOP 5 * FROM DEMO_Financial.Transactions;

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>3. Descriptive Statistics</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Values</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Use a Values analysis as the first type of analysis performed on unknown data. Values analysis determines the nature and quality of the data. For example, whether the data is categorical or continuously numeric, how many null values it contains, and so on.  A Values analysis provides a count of rows, rows with non-null values, rows with null values, rows with value 0, rows with a positive value, rows with a negative value, and the number of rows containing blanks in the given column. By default, unique values are counted, but this calculation can be inhibited for performance reasons if desired.  For a column of non-numeric type, the zero, positive, and negative counts are always zero (for example, 000 is not counted as 0).  A Values analysis can be performed on columns of any data type, though the measures displayed vary according to column type.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=c1,c2,c3. When columns=all is entered, all columns in the input table are analyzed.  Other options include allnumeric and allcharacter.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the table to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table containing the columns to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **Values**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Values parameter:</p>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Is required</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Must be the first parameter</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Is always enclosed in single quotes</li>
<p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **gensqlonly**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, the SQL for the requested function is returned as a result set but not run. When not specified or set to false, the SQL is run but not returned.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **groupby**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If columns are specified with the groupby parameter, a separate analysis is performed for each value or combination of values in the specified columns. For example: groupby=gender,marital_status.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the database to contain the analysis results table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the table to store the analysis results. If not supplied, the results are returned as a result set.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **uniques**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The unique values count for each selected column when this parameter is set to true. By default, the uniques parameter is set to false and not counted.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>- **where**</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the SQL WHERE clause generated within the Histogram SQL to filter rows selected for analysis. For example: where=cust_id > 0.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. First call the Values function on all columns in the customer table, including a count of unique values.</p>

In [ ]:
call val.td_analyze('Values',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=all;
                          uniques=true');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Chart Unique Values</b></p>

In [ ]:
%chart x=xcol, y=xunique, title="Unique Values", labelx=Column Name, labely=#Unique Values

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The above Chart shows Unique Values of columns from the Customer table. The X axis represents the columns and the Y axis has count of unique values in these columns.</p>

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>4. Statistics</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When working with numeric data columns, use statistical measures to understand the characteristics and properties of each numeric column, and to look for outlying values and anomalies. The Statistics analysis provides several common and not so common statistical measures for numeric data columns. Extended options include additional analyses and measures such as Values, Modes, Quantiles, and Ranks. You can perform Statistics analysis on columns of numeric or date data type. For columns of type DATE, statistics other than count, minimum, maximum, and mean are calculated by first converting to the number of days since 1900.
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=c1,c2,c3. When columns=all is entered, all columns in the input table are analyzed.  Other options include allnumeric and allnumericanddate.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the table to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **Statistics**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Statistics parameter:</p>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Is required</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Must be the first parameter</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>Is always enclosed in single quotes</li>
<p>    

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table containing the columns to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **extendedoptions**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Use to request any of the following extended options to be calculated:</p>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>all</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>none (default if extendedoptions is not specified)</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>modes</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>quantiles</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>values</li>
    <li style = 'font-size:16px;font-family:Arial;color:#00233C'>rank</li>
<p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **gensqlonly**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, the SQL for the requested function is returned as a result set but not run. When not specified or set to false, the SQL is run but not returned.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **groupby**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If columns are specified with the groupby parameter, a separate analysis is performed for each value or combination of values in the specified columns. For example:  groupby=gender,marital_status.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the database to contain the analysis results table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the table to store the analysis results. If not supplied, the results are returned as a result set.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statisticalmethod**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The calculated statistic as specified by either population or sample. For example, you can specify either statisicalmethod=population or statisticalmethod=sample. Population statistics is the default if neither is specified.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statsoptions**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The basic statistics to be calculated if the Statistics analysis is performed. You can use shortened aliases instead of the lengthier names (for example, statsoptions=all or statsoptions=cnt,min,max,mean,std). Available statistics include:</p>

<li style = 'font-size:16px;font-family:Arial;color:#00233C'>all</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>none</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>count (cnt)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>minimum (min)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>maximum (max)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>mean</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>standarddeviation (std)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>skewness (skew)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>kurtosis (kurt)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>standarderror (ste)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>coefficientofvariance (cv)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>variance (var)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>sum</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>uncorrectedsumofsquares (uss)</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>correctedsumofsquares (css)</li>
<p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **where**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The optional WHERE clause to filter the data to process. For example:  where=cust_id > 0</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. First call the Statistics function on the income, age, nbr_children and years_with_bank columns in the Customer table, taking basic statistics (min/max/mean/std).</p>

In [ ]:
call val.td_analyze('Statistics',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income,age,nbr_children,years_with_bank');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>2. Next call the Statistics function on the same variables in the Customer table, generating all statistics, including the extended options.</p>

In [ ]:
call val.td_analyze('Statistics',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income,age,nbr_children,years_with_bank;
                          statsoptions=all;
                          extendedoptions=all;');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>3. Finally call the Statistics function on the same variables in the Customer table, taking basic statistics (min/max/mean/std), this time grouping by gender.</p>

In [ ]:
call val.td_analyze('Statistics',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income,age,nbr_children,years_with_bank;
                          groupby=gender;');

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>5. Frequency</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A Frequency analysis counts the occurrences of individual data values in columns that contain categorical data. Frequency analysis is useful in understanding the meaning of a particular data element and can point out the need to recode some of the data values found, either permanently or in the course of building an analytic data set. This function is also useful in analyzing combinations of values occurring in two or more columns. A Frequency analysis calculates the number of occurrences of each value of the column or columns individually or in combination. Additionally, for each value, the percentage of rows in the selected table is provided in descending order starting with the most frequently occurring value. You can perform Frequency analysis on columns of any data type except types that hold byte data (for example, BYTE and VARBYTE).</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=c1,c2,c3. When columns=all is entered, all columns in the input table are analyzed.  Other options include allnumeric and allcharacter.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the table to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **frequency**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The frequency parameter:</p>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Is required</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Must be the first parameter</li>
<li style = 'font-size:16px;font-family:Arial;color:#00233C'>Is always enclosed in single quotes</li>
<p>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>**tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table containing the columns to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **cumulativeoption**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, includes rank, cumulative count, and cumulative percent information for each frequency value. This option is not available if the pairwise style is selected.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **gensqlonly**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, the SQL for the requested function is returned as a result set but not run. When not specified or set to false, the SQL is run but not returned.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **having**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Causes the specified SQL HAVING clause, generated within the Frequency SQL, to restrict returned aggregations. For example: having=xpct > 1. This option is valid only if the minimumpercentage option is not used.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **minimumpercentage**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If specified, the analysis includes only frequency values that occur a minimum percentage of the time, determined by the value of this parameter. Setting this to 0 or 0.0 is equivalent to not including the parameter at all.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the database to contain the analysis results table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the table to store the analysis results. If not supplied, the results are returned as a result set.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **pairwisecolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to be paired up with the frequency columns. Only use this option when the style parameter is set to pairwise.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statisticscolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If statistics columns are specified with this option, the minimum, maximum, mean value, and standard deviation of each column are included in the result set or answer table with the values computed over the rows corresponding to the individual values of the frequency columns. This option is available only with the basic frequency style and not with pairwise or crosstab.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **style**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>This option sets the frequency style to one of three values.</p>

<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Style</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>basic</td>
    <td>Counts frequencies of individual column values (default).</td>
  </tr>
  <tr>
    <td>pairwise</td>
    <td>Counts frequencies of pair-wise combinations of values of selected columns rather than individually. Not available if the cumulative option is selected.</td>
  </tr>
  <tr>
    <td>crosstab</td>
    <td>Counts frequencies of combinations of values of selected columns rather than individually.</td>
  </tr>
</table>

<p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **topvalues**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Number of frequency values to include. Shows frequency only for the number of top occurring values entered. For example, topvalues=10. This option is enabled only if cumulativeoption is selected.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **where**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Causes the specified SQL WHERE clause, generated within the Frequency SQL, to filter rows selected for analysis. For example: where=cust_id > 0.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. First call the Frequency function on the years_with_bank column in the Customer table.</p>

In [ ]:
call val.td_analyze('frequency',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=years_with_bank;');

In [ ]:
%chart xval, xpct, title=Customer Years, labelx=Years, labely=Percent

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The above Chart shows percentage of Customer Years. The X axis represents the number of years and the Y axis has percentage of customers which are with the institution for the number of years.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>2. Next call the Frequency function on the gender and marital_status columns in the Customer table, generating a cross-tabulation.</p>

In [ ]:
call val.td_analyze('frequency',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=gender,marital_status;
                          style=crosstab;');

In [ ]:
%chart x=marital_status, y=xpct, title=Frequency Cross-tabulation, height=300, width=300, labelx=Marital Status, labely=Percentage,

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The above Chart shows percentage of Customer based on the marital status. The X axis represents the marital status and the Y axis has percentage of customers which are with the institution based on the marital status.</p>

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>6. Histogram</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Histogram analysis reveals the distribution of continuous numeric or date values in a column. Histogram analysis is also referred to as binning because it counts the occurrence of values in a series of numeric ranges called bins. The histogram analysis provides a number of ways to define bins, allowing multidimensional binning, overlaying of categorical data, and the calculation of numeric statistics within bins.  If you set the desired number of equal sized data bins, the desired number of bins with a nearly equal number of values, a desired width, or the specific boundaries, the Histogram analysis separates the data to show its distributional properties. It does this by separating the data by bin number and gives counts and percentages over the requested rows. Percentages always sum to 100%. Separate options are available to specify a number of equal sized data bins in which the analysis determines the minimum and maximum value, as well as a user-specified minimum and maximum value. If the minimum and maximum are specified, all values less than the minimum are put in bin 0, while all values greater than the maximum are put in bin N+1. The same is true when the boundary option is specified.  The Histogram analysis optionally provides subtotals within each bin of the count, percentage within the bin and percentage overall for each value or combination of values of one or more overlaid columns. Another option is provided to collect simple statistics for a binned column or another column of numeric or date type within the table, providing the minimum, maximum, mean, and standard deviation. When statistics are collected for a date type column, the standard deviation is given in units of days.  You can perform Histogram analysis on columns of numeric or date data type.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=c1,c2,c3. When columns=all is entered, all columns in the input table are analyzed.  Other options include allnumeric and allnumericanddate.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the table to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **histogram**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The histogram parameter:
    <li>Is required</li>
    <li>Must be the first parameter</li>
    <li>Is always enclosed in single quotes</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table containing the columns to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **bins style**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Use these options to define a bins style. You can use only one option at a time. If you do not specify a bins style, the default is bins=10.</p>

<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Option</th>
    <th>Description/Example</th>
  </tr>
  <tr>
    <td>bins</td>
    <td>The number of equal width bins to create.</td>
  </tr>
  <tr>
    <td></td>
    <td>For example, bins=5. If multiple columns are requested, multiple bin sizes may be specified, such as bins=5, 10. If fewer sizes are specified than columns, left-over columns are associated with the default size of 10 bins.</td>
  </tr>
  <tr>
    <td>widths</td>
    <td>The width of the bins to create. </td>
  </tr>
  <tr>
    <td></td>
    <td>For example, widths=100. If multiple columns are requested, multiple widths must be specified, such as widths=5, 10. If fewer sizes are specified than columns, an error message displays.</td>
  </tr>
  <tr>
    <td>quantiles</td>
    <td>The number of approximately equally populated bins to create.</td>
  </tr>    
  <tr>
    <td></td>
    <td>For example, quantiles=10. If multiple columns are requested, multiple quantile sizes may be specified, such as quantiles=5, 10. If fewer sizes are specified than columns, left-over columns are associated with the default size of 10 quantiles.</td>
  </tr>
  <tr>
    <td>boundaries</td>
    <td>Specific boundaries that define the bins.</td>
  </tr>
  <tr>
    <td></td>
    <td>For example, boundaries=0,50,100,150 provides 3 bins between 0 and 150 (0 to 50, 50 to 100, and 100 to 150). If multiple columns are requested, multiple sets of parameters must be specified, such as boundaries={0, 50000, 100000, 150000}, {0, 50, 100}.</td>
  </tr>
  <tr>
    <td>binwithminmax</td>
    <td>The number of bins spanning a range specified by the minimum and maximum values.</td>
  </tr>
  <tr>
    <td></td>
    <td>For example, binwithminmax=5,0,200 creates 5 bins ranging from 0 to 200. If multiple columns are requested, multiple sets of parameters must be specified, such as binwithminmax={10, 0, 200000}, {5, 0, 100}.</td>
  </tr>      
</table>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **gensqlonly**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, the SQL for the requested function is returned as a result set but not run. When not specified or set to false, the SQL is run but not returned.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the database to contain the analysis results table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the table to store the analysis results. If not supplied, the results are returned as a result set.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overlaycolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A categorical variable with only a few values. If an overlay column is specified, frequencies within each bin are calculated for each value of that overlay column (frequencies for crosstabs of values are given if more than one overlay column is requested). You can use a specific column in either Overlay Columns or Statistics Columns, but not both.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statisticscolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Represents a list of numeric columns/aliases for which simple statistics are calculated (minimum,maximum, mean and standard deviation) in each bin. This option is not available for DATE columns. You can use a specific column in either Statistics Columns or Overlay Columns, but not both.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **style**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Sets the histogram style to one of two possible values:
<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Style</th>
    <th>Description/Example</th>
  </tr>
  <tr>
    <td>basic</td>
    <td>Creates a histogram for individual columns (default).</td>
  </tr>
  <tr>
    <td>crosstab</td>
    <td>Creates a multidimensional histogram by combining columns.</td>
  </tr>
</table>
</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **where**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the SQL WHERE clause generated within the Histogram SQL to filter rows selected for analysis. For example: where=cust_id > 0.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. First call the Histogram function on the income column in the Customer table, separating the data into 100 bins.</p>

In [ ]:
call val.td_analyze('histogram',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income;
                          bins=100');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Below bar chart shows the histogram from the above function.</p>

In [ ]:
%chart xbin, xcnt, title=Income Histogram-100 Bins, height=300, width=900, labelx=Bin Number, labely=Count of Customers

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A histogram is a graph used to represent the frequency distribution of a few data points of one variable. Histograms often classify data into various “bins” or “range groups” and count how many data points belong to each of those bins. In the above histogram the number of customers are distributed in different bins based on their income range. The number of bins in the above histogram is 100.</p>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'>2. Next call the Histogram function on the income column in the Customer table, performing a quantile binning, separating the data into 10 bins. The chart displays the quantiles.</p>

In [ ]:
call val.td_analyze('histogram',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income;
                          quantiles=10');

In [ ]:
%chart xbin, xcnt, title=Income Histogram-10 Quantiles, height=300, width=250, labelx=Bin Number, labely=Count

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>In the above histogram the number of customers are distributed in different quantiles based on their income range. The number of quantiles in the above histogram is 10.</p>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'>3. First call the Histogram function on the income and age columns in the Customer table performing a cross-tabulated quantile binning, separating the data into 10 bins.</p>

In [ ]:
call val.td_analyze('histogram',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income,age;
                          quantiles=10;
                          style=crosstab');

<hr style="height:2px;border:none;background-color:#00233C;">
<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>7. Adaptive Histogram</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Histogram analysis reveals the distribution of continuous numeric or date values in a column. Histogram analysis is also referred to as binning because it counts the occurrence of values in a series of numeric ranges called bins.  Adaptive Histogram analysis supplements Histogram analysis by offering options to further subdivide the distribution. You may specify the frequency percentage above which a single value should be treated as a Spike, and a similar percentage above which a bin should be subdivided.  The Adaptive Histogram analysis modifies the computed equal sized bins to include a separate bin for each spike value and to further subdivide a bin with an excessive number of values, returning counts and boundaries for each resulting bin.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The subdivision of a bin with too many values is performed by first dividing the bin by the same originally requested number of bins, and then merging this with a subdivision in the region around the mean value within the bin, the region being the mean +/- the standard deviation of the values in the bin.  Subdividing may optionally be performed using quantiles, giving approximately equally distributed sub-bins. (The quantiles option is not recommended however for tables with extremely large numbers of rows, such as input tables with billions of rows.)</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Adaptive binning can reduce the number of function calls needed to understand the distribution of the values assumed by a column.  Without adaptive binning, spike values and/or overpopulated bins can distort the bin counts, as they are not separated or subdivided unless the Adaptive Histogram function is used. It should however be noted that adaptive binning does not offer many of the specialized options that the standard Histogram analysis does.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=c1,c2,c3. When columns=all is entered, all columns in the input table are analyzed.  Other options include allnumeric and allnumericanddate.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the table to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **AdaptiveHistogram**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Adaptive Histogram parameter:
    <li>Is required</li>
    <li>Must be the first parameter</li>
    <li>Is always enclosed in single quotes</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table containing the columns to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **bins**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The number of equal width bins to create. For example, bins=5. If multiple columns are requested, multiple bin sizes may be specified, such as bins=5, 10. If fewer sizes are specified than columns, leftover columns are associated with the default size of 10 bins.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **gensqlonly**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, the SQL for the requested function is returned as a result set but not run. When not specified or set to false, the SQL is run but not returned.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the database to contain the analysis results table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the name of the table to store the analysis results. If not supplied, the results are returned as a result set.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **spikethreshold**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A percentage of rows, expressed as an integer from 1 to 100, above which an individual value of a column is identified as a separate bin. The default percentage is 10% of the total number of rows. Values with this or a larger percentage of rows are identified as a Spike.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **subdivisionmethod**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>means — Option to subdivide bins with too many values using a range of +/- the standard deviation around the mean value in the bin.</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>quantiles — Option to subdivide bins with too many values using quantiles, giving approximately equally distributed bins.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **subdivisionthreshold**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A percentage of rows, expressed as an integer from 0 to 100, above which a bin is subdivided into sub-bins. The default percentage is 30% of the total number of rows. Bins with this or a larger percentage of rows are subdivided into sub-bins.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **where**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the SQL WHERE clause generated within the Adaptive Histogram SQL to filter rows selected for analysis.  For example: where=cust_id > 0.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1.  The following case has no special options, with 10 equal width bins created by default for the requested column.  The default value of 10 is used for spikethreshold, and 30 for subdivisionthreshold, with means as the default subdivisionmethod.</p>

In [ ]:
call val.td_analyze('AdaptiveHistogram',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income;');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>2.  The case below demonstrates two columns with different numbers of bins, 5 for income and 3 for age.  Threshold values and other parameters assume default values.</p>

In [ ]:
call val.td_analyze('AdaptiveHistogram',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income,age;
                          bins=5,3;');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>3.  The third case demonstrates setting spikethreshold, subdivisionthreshold, subdivisionmethod and where-clause to non-default values.  Also notice that since an output table is requested, a SELECT statement is included to display the results - also notice that the order by clause of 1,2,3,5,4 is critical to interpreting the resulting sub-bins correctly.</p>

In [ ]:
call val.td_analyze('AdaptiveHistogram',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=income;
                          bins=5;
                          spikethreshold=12;
                          subdivisionthreshold=24;
                          subdivisionmethod=quantiles;
                          where=cust_id>0;
                          outputdatabase=demo_user;
                          outputtablename=_adaptive_example3');

In [ ]:
SELECT TOP 5 * FROM demo_user._adaptive_example3 order by 1,2,3,5,4;

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>8. Correlation/Covariance Matrices</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Matrix Building builds a sum-of-squares-and-cross-products (SSCP) matrix or other derived matrix type from a table in a SQL Engine. Matrix Building does this by generating and running the SQL to call the CALCMATRIX table operator provided in the SQL Engine beginning with the 14.10 release. The results are stored either in a table or as a result set returned to the user. The purpose in building a matrix depends on the type of matrix built. For example, when a correlation matrix is built, view it to determine the correlations or relationships between the various columns in the matrix.  For more information about the CALCMATRIX table operator, see Teradata® Database SQL Functions, Operators, Expressions, and Predicates, B035-1145.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The input columns comprising the created matrix or matrices. The columns must reside in the table named with the tablename parameter, residing in the database named with the database parameter.  For example: columns=column1,column2,column3.  Do not use the following column names, as these are reserved for use by the CALCMATRIX table operator: rownum, rowname, c, or s.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the input table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The input table to build a matrix from.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **groupby**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If specified, group by columns divide the input table into parts, one for each combination of values in the group by columns. For each combination of values a separate matrix is built, though they are all stored in the same output table or result data set. The group by columns must reside in the table named with the tablename parameter. The default case is no group by columns.  For example: groupby=column1,column2,column3.  Do not use the column names rownum, rowname, c, or s, as these are reserved for use by the CALCMATRIX table operator.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **matrixoutput {COLUMNS|VARBYTE}**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Matrix output can either be returned as COLUMNS in a table or as VARBYTE values, one per column, in a reduced output table. The default is output returned as COLUMNS.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **matrixtype**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The following types of matrix can be built with this function. If not specified, a sum-of-squares-andcross-products (SSCP) matrix is built.</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>**SSCP** = sum-of-squares-and-cross-products matrix (the default)</li>
    <li>**ESSCP** = Extended-sum-of-squares-and-cross-products matrix</li>
    <li>**CSSCP** = Corrected-sum-of-squares-and-cross-products matrix</li>
    <li>**COV** = Covariance matrix</li>
    <li>**COR** = Correlation matrix</li>
    </p>    

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **nullhandling {ZERO|IGNORE}**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a value in a selected column is NULL, the row that contains the NULL value is by default omitted from processing (nullhandling=IGNORE), or the value may be replaced in calculations with zero through the use of this parameter (nullhandling=ZERO).</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

    The database that contains the resulting matrix output table. If outputdatabase and outputtablename are not both specified, a volatile output table with randomly generated name is created in the logon userdatabase and the results are returned to the user in a result data set.

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The name of the output table representing one or more matrices. If group by columns are specified, there is a matrix for each combination of group by column values.  Note that the output table must first be dropped by the user before executing the function if outputdatabase and outputtablename are both specified. If outputdatabase and outputtablename are not both specified, a volatile output table with randomly generated name is created in the logon userdatabase, and the result set is returned to the user instead.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **where**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>An optional conditional expression may be specified with this parameter, limiting the amount of data used to build the matrix.  For example: where=income>0</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. First call the Matrix function on the age, years_with_bank and nbr_children columns in the Customer table, generating correlations and handling nulls as 0's.</p>

In [ ]:
call val.td_analyze('matrix',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=age,years_with_bank,nbr_children;
                          matrixtype=COR;
                          nullhandling=zero');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>2. Next call the Matrix function on the age, years_with_bank and nbr_children columns in the Customer table, generating covariances and handling nulls as 0's.</p>

In [ ]:
call val.td_analyze('matrix',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=age,years_with_bank,nbr_children;
                          matrixtype=COV;
                          nullhandling=zero');

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>9. Text Field Analyzer</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

When working with character data it is useful to determine the data type and what data can be stored in the database. The Text Field Analyzer analyzes character data and distinguishes if the field is a numeric type, date, time, timestamp, or character data. Use the Text Field Analyzer to any type of character data. Noncharacter data types go unprocessed and are passed along to the output as defined in the input table.  Using a table name and the name of one or more columns, the Text Field Analyzer provides a series of tests to distinguish what the correct underlying type of each selected column should be. The first test performed on the column is the MIN and the MAX test. The MIN and MAX values of a column are retrieved from the database and tested to determine what type the values are. The next test is a sample test which retrieves a small sample of data for each column and again assesses what type they should be. The next test is for fields that were determined to be numeric and it tries to classify them in a more specific category if possible. For instance, a column that is considered a FLOAT type after the first two tests might really be a DECIMAL type with 2 decimal places (the extended numeric test is optional but by default is performed).  In the next test, a date type is validated to make sure all values in that column are truly dates. Finally, if requested, Unicode columns are tested to see if they contain only Latin characters. The extended Unicode analysis is optional and by default is not performed.  A Text Field Analyzer can be performed on columns of any character data type. Columns of non-character data type are passed along to the output as defined in the input table.

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=c1,c2,c3. When columns=all is entered, all columns in the input table are analyzed.  Other options include allcharacter.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the table to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Text Field Analyzer generates SQL to create a table with columns of proposed data types.  The outputdatabase parameter is used in this generated SQL to fully qualify the name of the output table with the output database. The SQL is not run by the analysis.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Text Field Analyzer generates SQL to create a table with columns of proposed data types. The outputtablename parameter is the name of the output table. The SQL is not run by the analysis.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table containing the columns to analyze.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **TextFieldAnalyzer**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The TextFieldAnalzer parameter:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>    
    <li>Is required</li>
    <li>Must be the first parameter</li>
    <li>Is always enclosed in single quotes</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **extendednumericanalysis**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Determines whether to process specific numeric types. By default extendednumericanalysis=true to process extends numeric analysis.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **extendedunicodeanalysis**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Determines if a column declared to contain Unicode characters actually contains only Latin characters is enabled by setting the extendedunicodeanalysis parameter to true. By default, extended Unicode analysis is not performed. This is equivalent to extendedunicodeanalysis=false.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columnstoexclude**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If a column specifier such as all is used in the columns parameter, the columnstoexclude parameter may be used to exclude specific columns from the analysis.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. Call the Text Field Analyzer function on all columns in the Customer table.</p>

In [ ]:
call val.td_analyze('TextFieldAnalyzer',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          columns=all;
                          gensqlonly=true;
                          outputdatabase=demo_user;
                          outputtablename=_val_text_field_analysis1;
                          extendednumericanalysis=true;
                          extendedunicodeanalysis=false;');

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>10. Data Explorer</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Purpose</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Data Explorer performs basic statistical analysis on a set of selected tables, or on selected columns from tables, in one or more databases. It stores results from four fundamental types of analysis based on simplified versions of the Descriptive Statistics analyses:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>Values</li>
<li>Statistics</li>
<li>Frequency</li>
<li>Histogram</li>
</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>An answer table is produced for each requested type of analysis, the output including requested database, table, and column names to allow results from multiple tables to be included in each answer table. Each analysis is selected individually, with the following exceptions:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>If Frequency is selected, Values must be selected.</li>
<li>If Histogram is selected, Values and Statistics must be selected, including the Count, Minimum, Maximum, Mean, and Standard Deviation.</li>
</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Data Explorer includes intelligence about which functions should be performed on which columns, with decisions based partly on column type and partly on obtained results. It also includes performance enhancements in the generated SQL to help minimize passes through the data. You can specify a separate SQL Where Clause for each of the input tables selected for analysis.  You can perform Values analysis on columns of any data type, though the measures displayed vary according to the column type.  You can perform Statistics analysis on columns of numeric or date data type. For columns of type DATE, statistics other than count, minimum, maximum and mean are calculated by first converting to the number of days since 1900.  You can perform Frequency analysis on columns of any data type except types that hold byte data (for example, BYTE and VARBYTE).  You can perform Histogram analysis on columns of numeric or date data type.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database or databases containing the table or tables to be analyzed.  The number of databases in the database parameter and the number of tables in the tablename parameter must be the same. They are matched by position, and you can repeat the database names. For example, database=d1,d1,d2 and tablename=t1,t2,t3 indicates d1.t1, d1.t2, and d2.t3 are the tables to analyze, with tables t1 and t2 both residing in database d1.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **DataExplorer**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The DataExplorer parameter:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>    
    <li>Is required</li>
    <li>Must be the first parameter</li>
    <li>Is always enclosed in single quotes</li>
</p>    

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The results of the analysis are stored in one or more tables in this database.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The table or tables containing the columns to analyze. For example, tablename=t1,t2,t3 indicates three tables (t1, t2, and t3) are to be analyzed. The number of databases in the database parameter and the number of tables in the tablename parameter must be the same.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **bins**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The number of bins to create if the Histogram analysis is performed. The default is 10.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **binstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The style of binning to perform if the Histogram analysis is performed. The options are binstyle=bins (default) and binstyle=quantiles.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The columns to analyze. For example, columns=C1,C2,C3.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **frequencyoutputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The frequency analysis function is run and an output table is created with the results. Specify a unique name to avoid overwriting previous results (for example,frequencyoutputtablename=FrequencyExampleOutputTableName). If no outputtablename parameters are specified when Data Explorer is performed, all analysis functions are run and all output tables are created with a default table name. The default table name for frequencyoutputtablename is TwmExploreFrequency.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **histogramoutputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The histogram analysis function is run and an output table is created with the results. Specify a unique name to avoid overwriting previous results (for example, histogramoutputtablename=HistogramExampleOutputTableName). If no outputtablename parameters are specified when Data Explorer is performed, all analysis functions are run and all output tables are created with a default table name. The default table name for histogramoutputtablename is TwmExploreHistogram.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **maxnumcombvalues**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The maximum number of combined values for frequency or histogram analysis. The default is 10000.</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b></b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **maxuniquecharvalues**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The maximum number of unique character values for unrestricted frequency analysis. The default value is 100.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **maxuniquenumvalues**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The maximum number of unique numeric or date values for frequency analysis. The default is 20.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **minrowsforcomb**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The minimum number of rows before frequency or histogram combining attempted. The default is 25000.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **restrictedfreqproc**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The restricted frequency processing including prominent values. The default is true.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **restrictedthreshold**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The minimum percentage of rows a value must occur in, for inclusion in results. The default is 1.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statisticalmethod**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The calculated statistic as specified by either population or sample. For example, you can specify either statisicalmethod=population or statisticalmethod=sample. Population statistics is the default if neither is specified.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statisticsoutputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The statistics analysis function is run and an output table is created with the results. Specify a unique name to avoid overwriting previous results (for example, statisticsoutputtablename=StatisticsExampleOutputTableName). If no outputtablename parameters are specified when Data Explorer is performed, all analysis functions are run and all output tables are created with a default table name. The default table name for statisticsoutputtablename is TwmExploreStatistics.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **statsoptions**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The basic statistics to be calculated if the Statistics analysis is performed. You can use shortened aliases instead of the lengthier names (for example, statsoptions=all or statsoptions=cnt,min,max,mean,std). Available statistics include:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>    
    <li>all</li>
    <li>none</li>
    <li>count (cnt)</li>
    <li>minimum (min)</li>
    <li>maximum (max)</li>
    <li>mean</li>
    <li>standarddeviation (std)</li>
    <li>skewness (skew)</li>
    <li>kurtosis (kurt)</li>
    <li>standarderror (ste)</li>
    <li>coefficientofvariance (cv)</li>
    <li>variance (var)</li>
    <li>sum</li>
    <li>uncorrectedsumofsquares (uss)</li>
    <li>correctedsumofsquares (css)</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **uniques**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The unique values count for each selected column when this parameter is set to true. By default, the uniques parameter is set to false and not counted.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **valueoutputtablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The value analysis function is run and an output table is created with the results. Specify a unique name to avoid overwriting previous results (for example, valuesoutputtablename=ValuesExampleOutputTableName). If no outputtablename parameters are specified when Data Explorer is performed, all analysis functions are run and all output tables are created with a default table name. The default table name for valuesoutputtablename is TwmExploreValues.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **where**</b></p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The optional WHERE clause to filter the data to process. For example:  where=cust_id > 0</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1. First call the Data Explorer function on all columns in the Customer table.  Then select the results from each of the default generated output tables for the Values function (TwmExploreValues), Statistics function (TwmExploreStatistics), the Frequency function (TwmExploreFrequency) and the Histogram function (TwmExploreHistogram).</p>

In [ ]:
call val.td_analyze('DataExplorer',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          outputdatabase=demo_user;');

In [ ]:
select TOP 5 * from demo_user.TwmExploreValues order by 1,2,3,4

In [ ]:
select TOP 5 * from demo_user.TwmExploreStatistics order by 1,2,3,4

In [ ]:
select TOP 5 * from demo_user.TwmExploreFrequency where xcol='state_code' order by 1,2,3,4

In [ ]:
%chart x=xval, y=xpct, title=State Frequency, height=300, width=1000, labelx=State Code, labely=Percentage,

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>In the above graph we show the percentage of customers in different states.</p>

In [ ]:
select TOP 5 * from demo_user.TwmExploreHistogram order by 1,2,3,4

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>11. Variable Transformation</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Variable Transformation analysis reads a single table or view and produces a Select, Create Table, or Create View statement containing transformed columns. This is useful when preparing data for input to an
analytic algorithm. For example, a K-Means clustering algorithm typically produces better results when the
input columns are first converted to their Z-Score values to put all input variables on an equal footing,
regardless of their magnitude.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Syntax Conventions</b></p>

<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Object</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>{ }</td>
    <td>Encloses multiple transformations</td>
  </tr>
  <tr>
    <td>( )</td>
    <td>Encloses a list of values</td>
  </tr>
  <tr>
    <td> , </td>
    <td>Separates a list of transformation parameters</td>
  </tr>
  <tr>
    <td> ; </td>
    <td> Separates general parameters </td>
  </tr>
  <tr>
    <td> /column name </td>
    <td>Creates an output column with the specified column name</td>
  </tr>
  <tr>
    <td> ' </td>
    <td>Encloses a formula</td>
  </tr>   
</table>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Transformations</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Each call to td_analyze allows as many transformations within the limits of Teradata SQL. The first parameter is the vartran function name, followed by general parameters that apply to all of the requested transformations.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters for all Transformations</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **columns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Controls the name of the output (transformed) column and its data type. The columns parameter is required by all transformations except Derive. A separate transformation is performed for each column in the list. If a column name is followed by a forward slash and a name, the name after the slash becomes the name of the transformed column in the resultant output table. Otherwise the column name is used as the output column name. For the Derive transformation, the outputname parameter controls the naming of the transformed output column.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **database**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the input table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **tablename**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The input table to build a predictive model from.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **vartran**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Required to run a variable transformation. Enclose the 'vartran' parameter in single quotes.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Optional Parameters for all Transformations</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **datatype**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>For all transformation types, the datatype casts the column to a desired database data type provided it is compatible with the transformed data. Allowable output types include:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>byteint</li>
    <li>char</li>
    <li>date</li>
    <li>decimal</li>
    <li>float</li>
    <li>integer</li>
    <li>smallint</li>
    <li>time</li>
    <li>timestamp</li>
    <li>varchar</li>
    <li>bigint</li>
    <li>number</li>
    </p>    

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **fallback**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, requests a mirrored copy of the output table in the SQL Engine when outputstyle=table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **gensqlonly**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, the SQL for the requested transformations is returned as a result set but not run. When not specified or set to false, the SQL is run but not returned.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **indexcolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, requests the output table contain the index columns when outputstyle=table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **indexunique**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, requests the output table contain a unique primary index when outputstyle=table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **keycolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When null replacement is requested, either through a Null Replacement transformation or in combination with a Bin Code, Derive, Design Code, Recode, Rescale, Sigmoid, or Z Score transformation, the keycolumns parameter must be specified. The column or columns listed must form a unique key into the input and output table of the transformation.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **lockingclause**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Requests the generated SQL contain the given locking clause in the appropriate location depending on the output style.  An example of a locking clause when the output style defaults to select is:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`LOCKING mydb.mytable FOR ACCESS;`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **multiset**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, requests an output table that can contain duplicate rows when outputstyle=table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **noindex**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When true, requests the output table contain no index columns when outputstyle=table.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **nullstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Although NULL value replacement can be called individually, each transform supports it as well, just in case the derivation results in a NULL.  Data types supported by various nullstyle parameters are:</p>

<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Data Type</th>
    <th>Description</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>literal,value</td>
    <td>numeric, character, and date</td>
    <td>nullstyle (literal,value)</td>  
  </tr>
  <tr>
    <td>mean</td>
    <td>numeric and date</td>
    <td>nullstyle (mean)</td>
  </tr>
  <tr>
    <td>median</td>
    <td>numeric and date</td>
    <td>nullstyle (median)</td>  
  </tr>
  <tr>
    <td>medianwithoutaveraging</td>
    <td>any supported data type</td>
    <td>nullstyle (medianwithoutaveraging)</td> 
  </tr>
  <tr>
    <td>mode</td>
    <td>any supported date type</td>
    <td>nullstyle (mode)</td>
  </tr>
  <tr>
    <td>imputed,table</td>
    <td>any supported data type</td>
    <td>nullstyle (imputed,tablename)</td>  
  </tr>   
</table>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If date values are entered, the keyword DATE must precede the date value, and do not enclose in single quotes.</p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputdatabase**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The database containing the resulting output table when outputstyle=table or view.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Allowed output styles are:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>select</li>
    <li>table</li>
    <li>view</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If outputstyle is not specified, the function generates a SELECT statement and does not create a table or view.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **outputtablename**</b></p>
    
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The name of the output table when outputstyle=table or view.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **overwrite**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When overwrite is set to true (default), the output tables are dropped before creating new ones.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **whereclause**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Requests the generated SQL containing the given WHERE clause in appropriate places in the generated SQL. This is independent of the output style requested.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Bin Coding</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Bin Coding replaces a continuous numeric column with a categorical one and produce ordinal values (for example, numeric categorical values where order is meaningful). Bin Coding uses the same techniques used in Histogram analysis, allowing you to choose between equal-width bins, equal-width bins with a user-specified minimum and maximum range, bins with a user-specified width, evenly distributed bins, or bins with user-specified boundaries.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **bincode**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **binstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The binstyle parameter has five parameters. The style and one or more numeric or date values are placed in parentheses after the keyword binstyle. If this parameter is not specified, 10 equal width bins are created by default.  Allowable binstyle includes:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Syntax</th>
    <th>Examples</th>
  </tr>
  <tr>
    <td>binstyle (bins,nbr of bins)</td>
    <td>binstyle (bins,10)</td>
  </tr>
  <tr>
    <td>binstyle (binswithboundaries,nbr of bins,lower bound,upper bound)</td>
    <td>binstyle (binswithboundaries,5,0,100)</td>
  </tr>
  <tr>
    <td> </td>
    <td>This example specifies 5 equal-width bins between the boundaries 0 and 100.</td>
  </tr>
  <tr>
    <td> </td>
    <td>All values less than the minimum are put in to bin 0, while all values greater than the maximum are put into bin N+1.</td>
  </tr>
  <tr>
    <td>binstyle (boundaries,b1,b2,…)</td>
    <td>binstyle (boundaries, 0, 25, 50, 100)</td>
  </tr>
  <tr>
    <td> </td>
    <td>This example specifies bins between 0 and 25, 25 and 50, and 50 and 100.</td>
  </tr>  
  <tr>
    <td> </td>
    <td>All values less than the first boundary value are put in to bin 0, while all values greater than the last boundary value are put into bin N+1.</td>
  </tr>
  <tr>
    <td>binstyle (quantiles,nbr of quantiles)</td>
    <td>binstyle (quantiles,10)</td>
  </tr>
  <tr>
    <td> </td>
    <td>This example specifies 10 approximately evenly distributed bins, with roughly the same number of observations allocated to each bin.</td>
  </tr>
  <tr>
    <td>binstyle (width,bin width)</td>
    <td>binstyle (width,10)</td>
  </tr>
  <tr>
    <td> </td>
    <td>This example automatically calculates the minimum and maximum values of the column, then beginning with the observations with the minimum value, bins are assigned using the requested width of 10.</td>
  </tr>  
</table>
</p>


<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Formula Derivations - Derive</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Derive transformation requires the free-form transformation be specified as a formula using the following operators, arguments, and functions:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`+, -, **, *, /, %, (, ), x, y, z, abs, exp, ln, log, sqrt`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The arguments x, y, and z can only assume the value of an input column, unlike in the classic version of this transformation. Enclose the formula in pairs of single quotes for correct processing (see example below). An implied multiply operator is automatically inserted when a number, argument (x, y, z), or parenthesis is immediately followed by an argument or parenthesis. For example, 4x means 4*x, xy means x*y, and x(x+1) is equivalent to x*(x+1).</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>An example formula for the quadratic equation is below.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`formula (''(-y+sqrt(y**2-4xz))/(2x)'')`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **arguments**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the columns is associated with the arguments x, y, and z. If the formula parameter includes only the argument x, then the arguments parameter includes only one column. If the formula includes the arguments x and y, then the arguments parameter includes two column names. And finally, if the formula includes the arguments x, y, and z, the arguments parameter includes three column names.  In the case where the formula defines a constant expression, the arguments parameter is not required. However, at least one column must be included in the overall transformation, for example, in a Retain transformation.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **derive**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **formula**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The Derive transformation requires the free-form transformation is specified as a formula using the following operators, arguments, and functions:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`+, -, **, *, /, %, (, ), x, y, z, abs, exp, ln, log, sqrt`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The arguments x, y, and z can only assume the value of an input column, unlike in the classic version of this transformation. Enclose the formula in pairs of single quotes. An implied multiply operator is automatically inserted when a number, argument (x, y, z) or parenthesis is immediately followed by an argument or parenthesis. For example, 4x means 4*x, xy means x*y, and x(x+1) is equivalent to x*(x+1).</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Design Coding</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Design Coding is useful when a categorical data element must be re-expressed as one or more numeric data elements, creating a binary numeric field for each categorical data value. Design coding is offered in two forms: dummy-coding and contrast-coding.  In dummy-coding, a new column is produced for each listed value, with a value of 0 or 1 depending on whether that value is assumed by the original column. Alternately, given a list of values to contrast-code along with a reference value, a new column is produced for each listed value, with a value of 0 or 1 depending on whether that value is assumed by the original column, or a value of -1 if that original value is equal to the reference value.   When using dummy-coding, if a column assumes n values, new columns can be created for all n values, (or for only n-1 values, because the nth column is perfectly correlated with the first n-1 columns). When using contrast-coding, only n-1 or fewer new columns can be created from a categorical column with n values.  Design Coding supports character, numeric, and date type columns. If you enter date values, the keyword
DATE must precede the date value, do not enclose in single quotes. The following parameters are required for a Design Code transformation:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>designstyle</li>
    <li>designvalues</li>
    <li>columns</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **designcode**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **designstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The designstyle parameter can assume one of two different styles: dummycode or contrastcode</p>    


<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Style</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>designstyle (dummycode)</td>
    <td>In dummy-coding, a new column is produced for each listed value (see designvalues below), with a value of 0 or 1 depending on whether that value is assumed by the original column.</td>
  </tr>
  <tr>
    <td>designstyle (contrastcode, "reference value")</td>
    <td>Given a list of values to contrast-code, along with a reference value, a new column is produced for each listed value, with a value of 0 or 1 depending on whether that value is assumed by the original column, or a value of -1 if that original value is equal to the reference value. For example, with a reference value of 0:</td>
  </tr>
  <tr>
    <td> </td>
    <td>designstyle (contrastcode,0) </td>
  </tr>
</table>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **designvalues**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Lists the values to code and optionally the name of the resulting output column. For example:  designvalues(M/Males,F/Females)</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Recoding</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Recoding a categorical data column is done to re-express existing values of a column (variable) into a new coding scheme or to correct data quality problems and focus an analysis on a particular value. It allows for mapping individual values, NULL values, or any number of remaining values (ELSE option) to a new value, a NULL value or the same value.  Recoding supports character, numeric, and date type columns. If date values are entered, the keyword DATE must precede the date value, and do not enclose in single quotes.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **recode**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **recodeother**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the value assumed for all other cases. For example: recodeother(SAME).  Values allowed are:</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>    
    <li>SAME</li>
    <li>NULL</li>
    <li>A literal value</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **recodevalues**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Lists the values to be recoded, alternating the old and new column values separated by a slash.  For example: recodevalues(F/f,M/SAME,NULL/0).  The keyword SAME is used for the same value.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Rescaling</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Rescaling limits the upper and lower boundaries of the data in a continuous numeric column using a linear rescaling function based on maximum and minimum data values. Rescale is useful with algorithms that require or work better with data within a certain range. Rescale is only valid on numeric columns, and not columns of type date.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>You can supply new minimum and maximum values to form new variable boundaries. If only the lower boundary is supplied, the variable is aligned to this value; if only an upper boundary value is specified, the variable is aligned to that value. If a requested column has a constant value (max and min are the same), then the transformation fails with an SQL error.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The rescale transformation formulas are shown in the following examples. The l denotes the left bound and not the numeral 1, while r denotes the right bound.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When both the lower and upper bounds are specified:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`f(x,l,r) = (l+(x-min(x))(r-l))/(max(x)-min(x))`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When only the lower bound is specified:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`f(x,l) = x-min(x)+l`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When only the upper bound is specified:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>`f(x,r) = x-max(x)+r`</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Rescaling supports only numeric type columns.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **rescale**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **rescalebounds**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A slash to separate the keywords lowerbound and upperbound from the designated values. The third example is the default.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>rescalebounds(lowerbound/0)</li>
    <li>rescalebounds(upperbound/1)</li>
    <li>rescalebounds(lowerbound/0,upperbound/1)</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Sigmoid</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>A Sigmoid transformation provides rescaling of continuous numeric data in a more sophisticated way than the Rescaling transformation function. In a Sigmoid transformation a numeric column is transformed using a type of sigmoid or s-shaped function. The logit function produces a continuously increasing value between 0 and 1. The modified logit function is twice the logit minus 1 and produces a value between -1 and 1. The hyperbolic tangent function also produces a value between -1 and 1. These non-linear transformations are more useful in data mining than a linear Rescaling transformation.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **sigmoid**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>The parameter that identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **sigmoidstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Specifies the style of sigmoid function, either logit, modifiedlogit, or tanh (for example, hyperbolic tangent). If sigmoidstyle is not specified, the logit style is the default.</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
    <li>sigmoidstyle(logit)</li>
    <li>sigmoidstyle(modifiedlogit)</li>
    <li>sigmoidstyle(tanh)</li>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Z-Score</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Similar to a Sigmoid transformation, a Z-Score transformation provides rescaling of continuous numeric data in a more sophisticated way than a Rescaling transformation. In a Z-Score transformation, a numeric column is transformed into its Z-score based on the mean value and standard deviation of the data in the column. Z-Score transforms each column value into the number of standard deviations from the mean value of the column. This non-linear transformation is useful in data mining rather than in a linear Rescaling transformation.  The Z-Score transformation supports both numeric and date type input data.</p>  

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Required Parameters</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **zscore**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>NULL Value Replacement</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>NULL value replacement is offered as a transformation function. A literal value, the mean, median, mode, or an imputed value joined from another table can be used as the replacement value. The median value can be requested with or without averaging of two middle values when there is an even number of values.  Literal value replacement is supported for numeric, character, and date data types. Mean value replacement is supported for columns of numeric type or date type. Median without averaging, mode, and imputed value replacement are valid for any supported type. Median with averaging is supported only for numeric and date type.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **keycolumns**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>When null replacement is requested, either through a Null Replacement transformation or in combination with a Bin Code, Derive, Design Code, Recode, Rescale, Sigmoid, or Z Score transformation, the keycolumns parameter must be specified. The column or columns listed must form a unique key into the input and output table of the transformation.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **nullreplacement**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Identifies the type of transformation being performed.</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>- **nullstyle**</b></p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>Data types supported by various nullstyle parameters are:</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>
<table style = 'font-size:14px;font-family:Arial;color:#00233C'>
  <tr>
    <th>Data Type</th>
    <th>Description</th>
      <th>Example</th> 
  </tr>
  <tr>
    <td>literal,value</td>
    <td>numeric, character, and date</td>
    <td>nullstyle (literal,value)</td> 
  </tr>
  <tr>
    <td>mean</td>
    <td>numeric and date</td>
    <td>nullstyle (mean)</td>  
  </tr>
  <tr>
    <td>median</td>
    <td>numeric and date</td>
    <td>nullstyle (median)</td>  
  </tr>
  <tr>
    <td>medianwithoutaveraging</td>
    <td>any supported data type</td>
    <td>nullstyle (medianwithoutaveraging)</td>  
  </tr>
  <tr>
    <td>mode</td>
    <td>any supported date type</td>
    <td>nullstyle (mode)</td>  
  </tr>
  <tr>
    <td>imputed,table</td>
    <td>any supported data type</td>
    <td>nullstyle (imputed,tablename)</td>  
  </tr>  
</table>
</p>

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>If date values are entered, the keyword DATE must precede the date value, and do not enclose in single quotes.</p>

<hr style="height:1px;border:none;background-color:#00233C;">

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>1.  Each transformation function can be called individually as shown for bincode below:</p>

In [ ]:
call val.td_analyze('vartran',
                         'database=DEMO_Financial;
                          tablename=Customer;
                          bincode={binstyle (bins,5),columns (cust_id/cid1,age/age1,income/inc1)}
                                  {binstyle (binswithboundaries,5,0,100),columns (cust_id/cid2,age/age2,income/inc2)}
                                  {binstyle (boundaries,0.0,100.0,200.00),columns (cust_id/cid3,age/age3,income/inc3)}
                                  {binstyle (width,25),columns (cust_id/cid4,age/age4,income/inc4)}
                                  {binstyle (quantiles,5),columns (cust_id/cid5,age/age5,income/inc5)};');

<p style = 'font-size:16px;font-family:Arial;color:#00233C'>2.  Alternately, each transformation function can be called inclusively as shown below:</p>

In [ ]:
call val.td_analyze('vartran','database=DEMO_Financial;tablename=Customer;keycolumns=cust_id;

retain=columns(cust_id);

bincode=

{binstyle(bins,3),columns(income/inc1)}
{binstyle(bins,4),columns(income/inc2)}
{binstyle(bins,5),columns(income/inc3)};

derive=

{formula(''x/10''),arguments(age),outputname(age1)}
{formula(x*10),arguments(age),outputname(age2)}
{formula(x+10),arguments(age),outputname(age3)};

designcode=

{designstyle(dummycode),designvalues(M,F),columns(gender)}
{designstyle(dummycode),designvalues(1,2,3,4),columns(marital_status)};

nullreplacement=

{nullstyle(literal,0),columns(postal_code)};

recode=

{recodevalues(1/S,2/M,3/S,4/S),recodeother(SAME),columns(marital_status/mar1)}
{recodevalues(1/B,2/A,3/B,4/B),recodeother(NULL),columns(marital_status/mar2)};

rescale=

{rescalebounds(lowerbound/0,upperbound/100),columns(age/age4)}
{rescalebounds(lowerbound/0),columns(age/age5)}
{rescalebounds(upperbound/100),columns(age/age6)};

sigmoid=

{sigmoidstyle(logit),columns(nbr_children/nbr1)}
{sigmoidstyle(modifiedlogit),columns(nbr_children/nbr2)}
{sigmoidstyle(tanh),columns(nbr_children/nbr3)};

zscore=columns(years_with_bank);

');

<hr style="height:2px;border:none;background-color:#00233C;">

<p style = 'font-size:20px;font-family:Arial;color:#00233C'><b>12. Cleanup</b></p>

<p style = 'font-size:18px;font-family:Arial;color:#00233C'><b>Databases and Tables</b></p>
<p style = 'font-size:18px;font-family:Arial;color:#00233C'>The following code will clean up tables and databases created above.</p>
<p style = 'font-size:16px;font-family:Arial;color:#00233C'><b>Note:</b> In case you plan to execute the other notebooks in the VantageAnalyticLibrary , do not run the <b>remove_data</b> procedure below. Also in case you are not removing the databases and tables here , please make sure that you do not execute the <b>get_data</b> procedure in the next VantageAnalyticLibrary notebook.</p>

In [ ]:
call remove_data('DEMO_Financial');

<footer style="padding-bottom:35px; background:#f9f9f9; border-bottom:3px solid #00233C">
    <div style="float:left;margin-top:14px">ClearScape Analytics™</div>
    <div style="float:right;">
        <div style="float:left; margin-top:14px">
            Copyright © Teradata Corporation - 2023. All Rights Reserved
        </div>
    </div>
</footer>