# Code and data retrieval from tdstone2 deployment

## 1 - Connect to Vantage

In [1]:
import teradataml as tdml
import json
tdml.__version__

'20.00.00.03'

In [2]:
import tdstone2
tdstone2.__version__

'0.1.5.3'

In [3]:
with open('../connections/me.json','r') as f:
    Param_ = json.load(f)

with open('../connections/csae2.json','r') as f:
    Param = json.load(f)

with open('../connections/csae.json','r') as f:
    Param_ = json.load(f)

with open('../connections/vantage24.json','r') as f:
    Param_ = json.load(f)

tdml.create_context(**Param)

Engine(teradatasql://:***@sto-xo0saiv0ot1sxmj2.env.clearscape.teradata.com?DATABASE=demo_user&user=DEMO_USER)

## 2 - Retrieve the hyper segmented model

In [4]:
from tdstone2.tdsfeature_engineering import FeatureEngineering
from tdstone2.tdshypermodel import HyperModel
from tdstone2.tdstone import TDStone
sto = TDStone(schema_name = Param['database'], SEARCHUIFDBPATH = Param['user'])

In [5]:
sto.list_hyper_models()

                                                       CREATION_DATE                              ID_MODEL                    ID_MAPPER_TRAINING                     ID_MAPPER_SCORING                                 METADATA
ID
533fd2f6-cdf9-4c18-bfd1-11f6c017a587  2025-01-08 06:28:41.130000-05:  0fe42030-d412-411b-9695-8571c07507a0  fca98df7-3e26-41f5-a8a8-0036c348fb9a  57d6b26b-7691-4de9-b465-1d48affe93a8  {"user": "dm250067", "project": "test"}
654b028b-741e-4a46-8e5d-d966ac8a07b1  2025-01-08 05:26:48.160000-05:  1feb2a86-622c-4c56-8e94-4c367d1a232e  05842693-ddf1-4589-8d7b-a7ea4e952b95  a93604aa-2204-45a6-b4f5-1edab0414da1  {"user": "dm250067", "project": "test"}
91fb8620-0b80-4cec-a8a5-e1de531e608e  2025-01-08 05:36:52.330000-05:  06e9bc9e-32f1-4f7b-88f9-5a09e1ac8204  72ef3ebe-73d5-4a13-89d3-e093b53c81d1  d14273b9-df63-444b-98ce-0bad17935b12  {"user": "dm250067", "project": "test"}
c5ef0032-dd20-4b48-817e-6fe7e3c42e55  2025-01-08 05:31:04.970000-05:  505ea202-bbf4-4b2c-9639-2a18176d97f1  dc1cdd3e-111f-440e-ae0e-c0b3336c0716  431b1e0c-57a4-4ae8-bb3e-3a2372349857  {"user": "dm250067", "project": "test"}
f17adbc1-cd51-4281-87ca-2fb179d4ccd0  2025-01-08 06:33:41.570000-05:  479b48a6-e0e5-4d18-b637-de6f1ee63d8a  2e06e335-a352-4480-805d-182f66dca5e7  cddb9b47-acc7-4638-a61b-802aea11f0d7  {"user": "dm250067", "project": "test"}

In [6]:
id = sto.list_hyper_models()[['ID']].to_pandas(num_rows=1).reset_index().iloc[0,0]
id

'91fb8620-0b80-4cec-a8a5-e1de531e608e'

In [7]:
existing_model = HyperModel(tdstone=sto)
existing_model.download(id=id)

In [8]:
code_and_data = existing_model.retrieve_code_and_data(with_data=True)

### Local Execution

In [9]:
exec(code_and_data['code'])

In [10]:
model = MyModel(**code_and_data['arguments'])

In [11]:
code_and_data['data']

,Partition_ID,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,flag,Y1,Y2,FOLD
0,9,10006,0.871504,-0.954701,-0.721237,-0.513759,0.160625,-0.095130,-0.359911,-0.866613,-0.764595,1,-0.316810,0,train
1,9,10009,-0.198558,1.559091,-0.249417,1.343959,-0.272781,-1.340933,-1.855852,-0.603787,-1.143700,0,1.679389,1,train
2,9,10010,0.295880,0.003716,0.017230,-0.898037,-0.713384,1.403307,0.095851,-1.572761,0.246692,0,0.306141,1,train
3,9,10011,-0.212624,-1.660332,1.738873,-1.592312,0.264526,-0.467621,-1.073326,-0.624567,0.248211,0,2.183759,1,train
4,9,10013,0.212185,2.166812,-0.126676,1.947497,0.139170,0.204304,-1.360677,-0.056851,2.291005,0,-0.946190,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9,10021,-2.814222,-1.029850,0.972065,-0.211522,-2.123968,-0.529418,1.044235,-0.893972,-1.895213,0,0.764656,1,train
9996,9,10012,0.061424,-1.307137,0.142505,-0.270409,-1.935772,0.187760,1.120110,0.437945,0.017305,0,1.521122,1,train
9997,9,10007,0.052546,1.607960,1.009577,1.178767,-0.311975,0.983675,-0.236003,0.146856,0.484527,0,-2.390192,0,train
9998,9,10005,-0.816144,0.606629,-0.333752,-0.851405,0.493893,1.301019,0.744651,-0.475093,-1.405122,0,0.717806,1,train
9999,9,10003,-1.393861,0.075193,-0.374245,0.227970,1.498170,1.049103,-1.126909,1.700484,-0.265599,0,2.864524,1,train

In [12]:
code_and_data['data'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Partition_ID  10000 non-null  int64
 1   ID            10000 non-null  int64
 2   X1            10000 non-null  float64
 3   X2            10000 non-null  float64
 4   X3            10000 non-null  float64
 5   X4            10000 non-null  float64
 6   X5            10000 non-null  float64
 7   X6            10000 non-null  float64
 8   X7            10000 non-null  float64
 9   X8            10000 non-null  float64
 10  X9            10000 non-null  float64
 11  flag          10000 non-null  int64
 12  Y1            10000 non-null  float64
 13  Y2            10000 non-null  int64
 14  FOLD          10000 non-null  object
dtypes: float64(10), int64(4), object(1)
memory usage: 1.1+ MB

In [13]:
model.fit(code_and_data['data'])

In [14]:
model.score(code_and_data['data'])

,Partition_ID,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,flag,Y1,Y2,FOLD,anomaly_prediction,decision_function,anomaly_score
0,9,10006,0.871504,-0.954701,-0.721237,-0.513759,0.160625,-0.095130,-0.359911,-0.866613,-0.764595,1,-0.316810,0,train,1,24.729679,46.477374
1,9,10009,-0.198558,1.559091,-0.249417,1.343959,-0.272781,-1.340933,-1.855852,-0.603787,-1.143700,0,1.679389,1,train,1,9.900661,31.648356
2,9,10010,0.295880,0.003716,0.017230,-0.898037,-0.713384,1.403307,0.095851,-1.572761,0.246692,0,0.306141,1,train,1,19.451651,41.199345
3,9,10011,-0.212624,-1.660332,1.738873,-1.592312,0.264526,-0.467621,-1.073326,-0.624567,0.248211,0,2.183759,1,train,1,11.309830,33.057525
4,9,10013,0.212185,2.166812,-0.126676,1.947497,0.139170,0.204304,-1.360677,-0.056851,2.291005,0,-0.946190,0,train,1,2.178863,23.926557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9,10021,-2.814222,-1.029850,0.972065,-0.211522,-2.123968,-0.529418,1.044235,-0.893972,-1.895213,0,0.764656,1,train,-1,-3.485717,18.261978
9996,9,10012,0.061424,-1.307137,0.142505,-0.270409,-1.935772,0.187760,1.120110,0.437945,0.017305,0,1.521122,1,train,1,17.598794,39.346489
9997,9,10007,0.052546,1.607960,1.009577,1.178767,-0.311975,0.983675,-0.236003,0.146856,0.484527,0,-2.390192,0,train,1,19.477690,41.225384
9998,9,10005,-0.816144,0.606629,-0.333752,-0.851405,0.493893,1.301019,0.744651,-0.475093,-1.405122,0,0.717806,1,train,1,19.012675,40.760369
9999,9,10003,-1.393861,0.075193,-0.374245,0.227970,1.498170,1.049103,-1.126909,1.700484,-0.265599,0,2.864524,1,train,1,11.790947,33.538642

## 3 - Retrieve the feature engineering reducer

In [15]:
sto.list_feature_engineering_models()

Empty DataFrame
Columns: [CREATION_DATE, ID_MODEL, ID_MAPPER, FEATURE_ENGINEERING_TYPE, METADATA]
Index: []

In [16]:
id = sto.list_feature_engineering_models()
id = id[id.FEATURE_ENGINEERING_TYPE == 'feature engineering reducer'][['ID','CREATION_DATE']].sort('CREATION_DATE',ascending=False).to_pandas(num_rows=1).reset_index()['ID'].values[0]
id

IndexError: index 0 is out of bounds for axis 0 with size 0

In [34]:
feature_engineering = FeatureEngineering(tdstone=sto)
feature_engineering.download(id=id)

In [35]:
code_and_data = feature_engineering.retrieve_code_and_data(with_data=True)

### Local Execution

In [36]:
exec(code_and_data['code'])

In [37]:
model = MyModel(**code_and_data['arguments'])

In [38]:
code_and_data['data']

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,flag,Y1,Y2,FOLD
Partition_ID,,,,,,,,,,,,,,
752,520001,0.368566,1.868404,1.281078,-1.424041,-1.552282,1.464214,0.689420,-0.146295,-0.983114,0,-2.692144,0,train
752,520002,1.491964,-1.265916,0.104103,0.042839,-0.013701,-1.899406,-0.595181,-0.581376,0.411782,1,0.210064,1,train
752,520003,2.308943,0.585972,0.805053,1.465674,-0.690397,-1.475772,-1.589200,0.690923,-0.015212,0,4.587568,1,train
752,520004,2.092011,-1.011576,-1.428946,1.620772,0.195151,-0.534356,0.733791,1.370838,-0.209833,0,0.603158,1,train
752,520005,-0.293059,0.013612,-0.396283,1.130603,0.442577,0.758694,-0.077748,0.977241,-0.105177,1,0.838594,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,529996,0.675569,0.395423,2.197227,2.844338,1.262130,0.566113,-0.510810,-1.563369,0.459384,1,1.243296,1,test
752,529997,-1.581242,-1.174889,-0.988284,0.892053,0.200522,-1.475181,-0.385194,0.162419,0.509097,0,1.716410,1,test
752,529998,1.613692,-0.027182,0.691005,0.451394,0.241329,-1.004919,-0.673476,-0.350521,0.500766,0,0.016001,0,test
752,529999,0.733387,-0.171588,1.272539,-0.441146,-0.303182,-1.265550,-1.136038,-1.725205,0.949550,1,4.673061,1,test
752,530000,0.889024,-0.451726,-0.417532,-2.074698,-1.053201,0.560795,-0.701871,1.005911,-1.135817,0,-0.121899,0,test

In [39]:
code_and_data['data'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 752 to 752
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10000 non-null  int64
 1   X1      10000 non-null  float64
 2   X2      10000 non-null  float64
 3   X3      10000 non-null  float64
 4   X4      10000 non-null  float64
 5   X5      10000 non-null  float64
 6   X6      10000 non-null  float64
 7   X7      10000 non-null  float64
 8   X8      10000 non-null  float64
 9   X9      10000 non-null  float64
 10  flag    10000 non-null  int64
 11  Y1      10000 non-null  float64
 12  Y2      10000 non-null  int64
 13  FOLD    10000 non-null  object
dtypes: float64(10), int64(3), object(1)
memory usage: 1.1+ MB

In [40]:
model.transform(code_and_data['data'])

{'X1_mean': -0.0104776588436281,
 'X2_mean': 0.01485421501362058,
 'X3_mean': -0.0018620420750028528,
 'X4_mean': 0.018781104920128307,
 'X5_mean': 0.0015796163635362276,
 'X6_mean': -0.005152479912380363,
 'X7_mean': 0.0139535004309788,
 'X8_mean': 0.015739483870488426,
 'X9_mean': 0.01712352716380503,
 'X1_max': 3.920030987117869,
 'X2_max': 3.621206036937945,
 'X3_max': 3.765003605362835,
 'X4_max': 4.105203804002776,
 'X5_max': 4.20734944976251,
 'X6_max': 3.75868586780327,
 'X7_max': 3.6978047658053868,
 'X8_max': 3.568084908715738,
 'X9_max': 3.5634158773147613}

## 4 - Retrieve the feature engineering

In [41]:
sto.list_feature_engineering_models()

                                                       CREATION_DATE                              ID_MODEL                             ID_MAPPER     FEATURE_ENGINEERING_TYPE                                 METADATA
ID
8ccffaf6-bfe0-415d-9792-ee97ae45ffe8  2024-04-12 03:25:23.830000-04:  02b54ae0-f70f-495a-ae96-f65dbc56391a  e6eafc04-cd1c-494d-9a19-594c183bb2c2  feature engineering reducer  {"user": "dm250067", "project": "test"}
2805bdd2-9fd6-463d-85d3-97fa1d35181d  2024-04-12 03:32:59.690000-04:  5513c8c0-b6c4-4e40-ba4a-87fe76448e44  f990338f-9b79-4c7b-beb1-db7acef068db          feature engineering  {"user": "dm250067", "project": "test"}
214b6494-9a84-4ce1-b774-14d38fb60b43  2024-04-12 03:52:05.190000-04:  c794259b-edee-46cc-a1b2-ef8c595fcab5  284016a2-b848-4458-bd19-b064c7e2322d  feature engineering reducer  {"user": "dm250067", "project": "test"}

In [42]:
id = sto.list_feature_engineering_models()
id = id[id.FEATURE_ENGINEERING_TYPE == 'feature engineering'][['ID']].to_pandas(num_rows=1).reset_index()['ID'].values[0]
id

'2805bdd2-9fd6-463d-85d3-97fa1d35181d'

In [43]:
feature_engineering = FeatureEngineering(tdstone=sto)
feature_engineering.download(id=id)

In [44]:
code_and_data = feature_engineering.retrieve_code_and_data(with_data=True)

### Local Execution

In [45]:
exec(code_and_data['code'])

In [46]:
model = MyModel(**code_and_data['arguments'])

In [47]:
code_and_data['data']

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,flag,Y1,Y2,FOLD
Partition_ID,,,,,,,,,,,,,,
277,1710001,-0.322763,1.676205,0.541605,-0.503736,0.184875,-0.275941,0.872859,-0.039254,-1.152262,1,1.129859,1,train
277,1710002,2.361259,1.405868,0.149997,-2.979406,-0.743130,-1.409789,-0.183668,0.059957,0.032516,0,3.927738,1,train
277,1710003,-1.400112,-0.199571,-0.550877,-0.596378,-0.792467,0.142952,-1.031222,-0.082852,0.311577,0,-1.165460,0,train
277,1710004,-0.437549,-0.065052,0.367380,1.833715,-0.202859,-0.117602,0.533036,0.309732,1.153471,1,0.658654,1,train
277,1710005,1.643022,-0.209526,-0.757674,1.811366,-0.581721,0.134779,-0.074586,0.592591,0.490082,0,-0.293187,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,1719996,-0.496574,2.850491,1.368755,-0.076942,0.344252,0.121435,-0.815227,-1.056180,-2.556958,1,-4.339742,0,test
277,1719997,0.131512,-0.035680,0.514531,1.662403,2.760186,-0.292216,-0.401263,1.162874,0.777606,1,-1.113218,0,test
277,1719998,-0.806880,-1.112085,-0.415337,-1.153708,1.683237,-0.184817,-0.411669,0.092694,0.020613,0,0.499478,1,test
277,1719999,1.417620,-0.264157,0.646673,-0.477578,-0.490204,1.278011,-1.529266,-0.215583,-0.711250,1,1.092707,1,test
277,1720000,0.194333,0.394189,-0.853574,-0.567825,0.309274,0.024629,2.213745,0.407159,0.084537,1,0.427985,1,test

In [48]:
code_and_data['data'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 277 to 277
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10000 non-null  int64
 1   X1      10000 non-null  float64
 2   X2      10000 non-null  float64
 3   X3      10000 non-null  float64
 4   X4      10000 non-null  float64
 5   X5      10000 non-null  float64
 6   X6      10000 non-null  float64
 7   X7      10000 non-null  float64
 8   X8      10000 non-null  float64
 9   X9      10000 non-null  float64
 10  flag    10000 non-null  int64
 11  Y1      10000 non-null  float64
 12  Y2      10000 non-null  int64
 13  FOLD    10000 non-null  object
dtypes: float64(10), int64(3), object(1)
memory usage: 1.1+ MB

In [49]:
model.transform(code_and_data['data'])

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,flag,Y1,Y2,FOLD,X1_x_X1,X1_x_X2,X2_x_X1,X2_x_X2
Partition_ID,,,,,,,,,,,,,,,,,,
277,1710001,-0.322763,1.676205,0.541605,-0.503736,0.184875,-0.275941,0.872859,-0.039254,-1.152262,1,1.129859,1,train,0.104176,-0.541018,-0.541018,2.809663
277,1710002,2.361259,1.405868,0.149997,-2.979406,-0.743130,-1.409789,-0.183668,0.059957,0.032516,0,3.927738,1,train,5.575543,3.319618,3.319618,1.976465
277,1710003,-1.400112,-0.199571,-0.550877,-0.596378,-0.792467,0.142952,-1.031222,-0.082852,0.311577,0,-1.165460,0,train,1.960315,0.279422,0.279422,0.039829
277,1710004,-0.437549,-0.065052,0.367380,1.833715,-0.202859,-0.117602,0.533036,0.309732,1.153471,1,0.658654,1,train,0.191449,0.028463,0.028463,0.004232
277,1710005,1.643022,-0.209526,-0.757674,1.811366,-0.581721,0.134779,-0.074586,0.592591,0.490082,0,-0.293187,0,train,2.699523,-0.344255,-0.344255,0.043901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,1719996,-0.496574,2.850491,1.368755,-0.076942,0.344252,0.121435,-0.815227,-1.056180,-2.556958,1,-4.339742,0,test,0.246585,-1.415479,-1.415479,8.125299
277,1719997,0.131512,-0.035680,0.514531,1.662403,2.760186,-0.292216,-0.401263,1.162874,0.777606,1,-1.113218,0,test,0.017295,-0.004692,-0.004692,0.001273
277,1719998,-0.806880,-1.112085,-0.415337,-1.153708,1.683237,-0.184817,-0.411669,0.092694,0.020613,0,0.499478,1,test,0.651055,0.897319,0.897319,1.236732
277,1719999,1.417620,-0.264157,0.646673,-0.477578,-0.490204,1.278011,-1.529266,-0.215583,-0.711250,1,1.092707,1,test,2.009646,-0.374474,-0.374474,0.069779
277,1720000,0.194333,0.394189,-0.853574,-0.567825,0.309274,0.024629,2.213745,0.407159,0.084537,1,0.427985,1,test,0.037766,0.076604,0.076604,0.155385

In [ ]:
tdml.remove_context()